Code Fix.
tradersclub/airbyte pull request #8
Opened 2021-11-04 04:28 UTC by cesarvspr

## What
Fix
Error when trying to get a dataset from a source.
```
"2021-11-04 04:22:04 ERROR () LineGobbler(voidCall):65 - UnboundLocalError: local variable 'headers' referenced before assignment"
```

## How
Declaring the variable properly.

2021-11-04 17:59 UTC, jcpribeirotc requested changes

2021-11-04 17:59 UTC, jcpribeirotc commented on airbyte-integrations/connectors/source-http-request/source_http_request/source.py
> +                    return datetime.today() - relativedelta(month = digit)
return datetime.today() - relativedelta(months = digit)

2021-11-04 17:59 UTC, jcpribeirotc commented on airbyte-integrations/connectors/source-http-request/source_http_request/source.py
> +                    return datetime.today() - relativedelta(year = digit)
return datetime.today() - relativedelta(years = digit)

2021-11-04 18:08 UTC, jcpribeirotc approved these changes

2021-11-05 11:14 UTC, rodrigo-morais-tc approved these changes
LGTM

2021-11-05 12:09 UTC, merged